#!/usr/bin/env python3
"""
log_timeline.py — Bucket-counts d'événements dans les logs timestampés par run.sh.

Précondition : logs préfixés `<epoch_sec> +<rel_sec>s` (CALYPSO_LOG_TS=1).

Sortie :
  - ASCII bar chart sur stdout (table par bucket)
  - CSV `/tmp/log_timeline.csv` (colonnes : t_rel, qemu, bridge, osmocon,
    mobile, tdma, frame_irq, kick, fb_det_hit, stack_in_ndb)

Pas de PNG ici — le plot est généré côté RStudio/Quarto via un chunk R
qui lit directement le CSV (chunk dans test_results.qmd auto-généré par
tests/conftest.py).

Usage :
    python3 log_timeline.py [--bucket-s 5] [--csv /tmp/foo.csv]
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

LOGS = {
    "qemu":    "/root/qemu.log",
    "bridge":  "/tmp/bridge.log",
    "osmocon": "/tmp/osmocon.log",
    "mobile":  "/tmp/mobile.log",
}
TS_RE = re.compile(r'^(\d+\.\d+)\s+\+(\d+\.\d+)s\s+(.*)$')

# Markers à compter individuellement dans qemu.log (timer events)
QEMU_TAGS = {
    "tdma":          re.compile(r'\[tdma\] tick'),
    "frame_irq":     re.compile(r'\[frame_irq\] lower'),
    "kick":          re.compile(r'\[kick\] fire'),
    "fb_det_hit":    re.compile(r'ARM RD d_fb_det .* = 0x0001'),
    "stack_in_ndb":  re.compile(r'STACK-IN-NDB'),
}


def parse_log(path: str) -> list[tuple[float, str]]:
    out = []
    try:
        with open(path, errors="replace") as f:
            for line in f:
                m = TS_RE.match(line)
                if m:
                    out.append((float(m.group(1)), m.group(3)))
    except FileNotFoundError:
        pass
    return out


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--bucket-s", type=float, default=5.0)
    p.add_argument("--csv", default="/tmp/log_timeline.csv")
    p.add_argument("--ascii-width", type=int, default=60)
    # --png kept as no-op for backward compat (silently ignored if passed)
    p.add_argument("--png", default=None, help="(no-op, plotting moved to RStudio/Quarto)")
    args = p.parse_args()

    # Parse all logs
    per_log: dict[str, list[tuple[float, str]]] = {
        name: parse_log(path) for name, path in LOGS.items()
    }
    # Find global t0
    all_ts = [t for samples in per_log.values() for t, _ in samples]
    if not all_ts:
        print("No timestamped data found in any log.", file=sys.stderr)
        sys.exit(2)
    t0 = min(all_ts)
    t_end = max(all_ts)
    n_buckets = max(1, int((t_end - t0) / args.bucket_s) + 1)
    print(f"Wall window : {t_end - t0:.1f}s  buckets={n_buckets}  bucket={args.bucket_s}s")

    # Buckets[i] = dict of counts
    buckets = [defaultdict(int) for _ in range(n_buckets)]

    for name, samples in per_log.items():
        for ts, body in samples:
            b = int((ts - t0) / args.bucket_s)
            if 0 <= b < n_buckets:
                buckets[b][name] += 1
                # Sub-tags for qemu
                if name == "qemu":
                    for tag, pat in QEMU_TAGS.items():
                        if pat.search(body):
                            buckets[b][tag] += 1

    # Series we'll track
    series = ["qemu", "bridge", "osmocon", "mobile",
              "tdma", "frame_irq", "kick", "fb_det_hit", "stack_in_ndb"]

    # CSV output
    with open(args.csv, "w") as fcsv:
        fcsv.write("t_rel," + ",".join(series) + "\n")
        for i, b in enumerate(buckets):
            t_rel = i * args.bucket_s
            row = [str(b.get(s, 0)) for s in series]
            fcsv.write(f"{t_rel:.1f}," + ",".join(row) + "\n")
    print(f"CSV written: {args.csv}")

    # ASCII chart per series — bar = log10 scale to handle wide rates
    print()
    print(f"{'t_rel':>7}  | " + " | ".join(f"{s[:8]:<8}" for s in series))
    print("-" * (10 + 11 * len(series)))
    for i, b in enumerate(buckets):
        t_rel = i * args.bucket_s
        cells = []
        for s in series:
            v = b.get(s, 0)
            cells.append(f"{v:8d}")
        print(f"{t_rel:7.1f}  | " + " | ".join(cells))

    # Plotting moved to RStudio/Quarto via R chunk reading CSV.
    # See test_results.qmd auto-generated by tests/conftest.py.
    print(f"\n(plotting handled by RStudio/Quarto from {args.csv})")


if __name__ == "__main__":
    main()
